# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      ALLURE_RESULTS: allure-results
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O ./allurectl
          chmod +x ./allurectl
      - run: ./allurectl watch -- ./gradlew test
