# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      ALLURE_TESTPLAN_PATH: ./testplan.json
      ALLURE_RESULTS: allure-results
    steps:
      - checkout
      - run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O ./allurectl
          chmod +x ./allurectl
      - run: ./allurectl job-run plan --output-file ${ALLURE_TESTPLAN_PATH}
      - run: ./allurectl watch -- ./gradlew test
